## Options ##

set -s escape-time 0    # Make programs like vim feel more responsive
set -g set-clipboard on # Use system clipboard


set -g bell-action none
set -g visual-bell off

set -g history-limit 50000
set -g base-index 1
set -g renumber-windows on

set -g allow-rename off

set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'bg=default'
set -g window-status-current-style 'fg=blue bold'
set -g status on
set -g status-left ''
set -g status-right ''
set -g mouse on

set -g pane-active-border-style 'fg=blue'

set -g cursor-style block

set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm*:civis@:cnorm@:cvvis@' # Stop blinking dammit!

setw -g mode-keys vi # vim-based keybinds

## Keybinds ##

# Quick reloading using <prefix>r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind '"'
unbind %
bind v split-window -h
unbind s
bind s split-window -v

unbind h
unbind j
unbind k
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
