# Text and background colors

foreground              #CDD6F4
background              #11111B

selection_foreground    #1E1E2E
selection_background    #F5E0DC

cursor                  #f0f0ff
cursor_text_color       #1E1E2E

url_color               #F5E0DC

# black
color0 #313244
color8 #45475A
# red
color1 #f38ba8
color9 #eba0ac
# green
color2  #a6e3a1
color10 #94e2d5
# yellow
color3  #f9e2af
color11 #fab387
# blue
color4  #89b4fa
color12 #b4befe
# magenta
color5  #cba6f7
color13 #f5c2e7
# cyan
color6  #89dceb
color14 #f5c2e7
# white
color7  #a6adc8
color15 #bac2de

# Tab bar

active_tab_foreground #11111B
active_tab_background #89b4fa
inactive_tab_foreground #bac2de
inactive_tab_background #313244
tab_bar_background      none

# Borders

active_border_color     #89b4fa
inactive_border_color   #585b70
bell_border_color       #F9E2AF

# Marks
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC
