# Bind commonly used alt keys to ctrl+alt

map ctrl+alt+b send_key alt+b
map ctrl+alt+f send_key alt+f

# Prefix keybinds

map --new-mode=p --on-action end --on-unknown end ctrl+s

map --mode=p shift+r load_config_file

map --mode=p s launch --cwd=current --location=hsplit
map --mode=p v launch --cwd=current --location=vsplit

map --mode=p h neighboring_window left
map --mode=p j neighboring_window down
map --mode=p k neighboring_window up
map --mode=p l neighboring_window right

map --mode=p shift+h move_window left
map --mode=p shift+j move_window down
map --mode=p shift+k move_window up
map --mode=p shift+l move_window right

map --mode=p f layout_action rotate

map --mode=p r set_tab_title " "
map --mode=p / search_scrollback
map --mode=p q close_window
map --mode=p c new_tab_with_cwd

map --mode=p - goto_tab -1
map --mode=p 1 goto_tab 1
map --mode=p 2 goto_tab 2
map --mode=p 3 goto_tab 3
map --mode=p 4 goto_tab 4
map --mode=p 5 goto_tab 5
map --mode=p 6 goto_tab 6
map --mode=p 7 goto_tab 7
map --mode=p 8 goto_tab 8
map --mode=p 9 goto_tab 9
map --mode=p 0 goto_tab 10

action_alias move_to_tab remote_control detach-window --self --target-tab
map --mode=p shift+1 move_to_tab index:0
map --mode=p shift+2 move_to_tab index:1
map --mode=p shift+3 move_to_tab index:2
map --mode=p shift+4 move_to_tab index:3
map --mode=p shift+5 move_to_tab index:4
map --mode=p shift+6 move_to_tab index:5
map --mode=p shift+7 move_to_tab index:6
map --mode=p shift+8 move_to_tab index:7
map --mode=p shift+9 move_to_tab index:8
map --mode=p shift+0 move_to_tab index:9

map --mode=p ctrl+s send_key ctrl+s

# Resize mode

map --new-mode=resize ctrl+b

map --mode=resize h resize_window narrower
map --mode=resize j resize_window taller
map --mode=resize k resize_window shorter
map --mode=resize l resize_window wider
map --mode=resize shift+h resize_window narrower 4
map --mode=resize shift+j resize_window taller 4
map --mode=resize shift+k resize_window shorter 4
map --mode=resize shift+l resize_window wider 4
map --mode=resize r resize_window reset
map --mode=resize - change_font_size current -1.0
map --mode=resize = change_font_size current +1.0
map --mode=resize backspace change_font_size current 0

map --mode=resize ctrl+b combine : pop_keyboard_mode : send_key ctrl+b

map --mode=resize esc pop_keyboard_mode
map --mode=resize q   pop_keyboard_mode
