# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

source = ~/.config/hypr/my-colors.conf

$font = Rubik

general {
    hide_cursor = true
    ignore_empty_input = true
    fractional_scaling = 1
    fail_timeout = 250
}

auth {
    fingerprint {
        enabled = false
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 500 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0

    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldColors, 1, 1, linear
    animation = inputFieldDots, 1, 1, linear
}

background {
    monitor =
    path = ~/.config/hypr/temp/current-wallpaper
    blur_size = 2
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    inner_color = $cBase
    outer_color = $cLavender $cBlue 45deg
    check_color = $cMauve $cLavender 45deg
    fail_color = $cPeach $cRed 45deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.2
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -100
    halign = center
    valign = center

    shadow_size = 2
    shadow_passes = 1
    shadow_color = rgb(17, 17, 27)
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 60
    font_family = $font

    position = 0, 100
    halign = center
    valign = center

    shadow_size = 2
    shadow_passes = 1
    shadow_color = rgb(17, 17, 27)
}

# DATE
label {
    monitor =
    text = cmd[update:1000] date +"%m/%d (%a)" # update every second
    font_size = 30
    font_family = $font

    position = 0, 25
    halign = center
    valign = center

    shadow_size = 2
    shadow_passes = 1
    shadow_color = rgb(17, 17, 27)
}
