# Colors from Catppuccin Mocha

$cRosewater = rgb(f5e0dc)
$cFlamingo = rgb(f2cdcd)
$cPink = rgb(f5c2e7)
$cMauve = rgb(cba6f7)
$cRed = rgb(f38ba8)
$cMaroon = rgb(eba0ac)
$cPeach = rgb(fab387)
$cYellow = rgb(f9e2af)
$cGreen = rgb(a6e3a1)
$cTeal = rgb(94e2d5)
$cSky = rgb(89dceb)
$cSapphire = rgb(74c7ec)
$cBlue = rgb(89b4fa)
$cLavender = rgb(b4befe)

$cText = rgb(cdd6f4)
$cSurface1 = rgb(45475a)
$cSurface0 = rgb(323244)
$cBase = rgb(1e1e2e)
$cMantle = rgb(181825)
$cCrust = rgb(11111b)
